name: Trackerslist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  trackerslist_autoupdate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script to trackerslist
        run: |
          python trackerslist.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update trackerslist"
          git push
