name: Trackerslist

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  trackerslist_autoupdate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Install sed
        run: |
          sudo apt-get update
          sudo apt-get install sed -y

      - name: Run script to trackerslist
        run: |
          python trackerslist.py

      - name: Add current merge time to trackerslist.txt
        run: |
          sed -i "1s/^/当前合并完成的时间: ${{ formatTime(now(), 'yyyy-MM-dd HH:mm:ss') }}\\n\n/" trackerslist.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update trackerslist"
          git push
